enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
version = "latest"
excluded-patches = "'Custom branding' 'Change header'"
